import { Toaster } from 'sonner'
import './globals.css'

import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Yii2 Model Generator',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
